"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Ifeanyichukwu Anyasinti this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ica368
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 10/21. If you choose to use
        # a dummy node, you can comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        """"Insert term function"""
        nnode = Node(coeff,exp,None)

        if self.head is None or self.head.exp < exp:
            nnode.next = self.head
            self.head = nnode
            return

        cur = self.head

        while cur.next is not None:

            if cur.next.exp == exp:
                cur.coeff += coeff
            elif cur.next.exp < exp:
                nnode.next = cur.next
                cur.next = nnode
                return
            cur = cur.next

            if cur.next is None:
                nnode.next = None
                cur.next = nnode
                return


    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        """Adding two polynomials"""
        np = LinkedList()
        cur = self.head
        cur_p = p.head

        while cur is not None and cur_p is not None:
            if cur.exp > cur_p.exp:
                np.insert_term(cur.coeff,cur.exp)
            elif cur.exp < cur_p.exp:
                np.insert_term(cur_p.coeff,cur_p.exp)
            elif cur.exp == cur_p.exp:
                cur.coeff += cur_p.coeff
                np.insert_term(cur.coeff,cur.exp)

            cur = cur.next
            cur_p = cur_p.next
        return np


    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        """Multiply Polynomial"""
        np = LinkedList()
        cur = self.head


        while cur is not None:
            cur_p = p.head
            while cur_p is not None:
                ncoeff = cur.coeff * cur_p.coeff
                nexp = cur.exp + cur_p.exp
                np.insert_term(ncoeff,nexp)
                cur_p = cur_p.next

            cur = cur.next
        return np


    # Return a string representation of the polynomial.
    def __str__(self):
        """String representation"""
        l = []
        cur = self.head

        while cur is not None:
            l.append(str((cur.coeff, cur.exp)))
            cur = cur.next

        string = " + ".join(l)
        return string


def main():
    """Main"""
    # read data from stdin using input() and create polynomial p

    # read data from stdin using input() and create polynomial q

    # get sum of p and q as a new linked list and print sum

    # get product of p and q as a new linked list and print product

    pn = input()
    head = None
    cur = None

    for _ in range(pn):
        cur_line = input().strip()
        nnode = Node(None,None,None)
        if cur_line[0] == "-":
            nnode.coeff = -1 * int(cur_line[1])
        else:
            nnode.coeff = cur_line[0]
        if cur_line[2] == "-":
            nnode.exp = -1 * int(cur_line[3])
        else:
            nnode.exp = cur_line[2]

        if head == None:
            head = nnode
            cur = nnode
        else:
            cur.next = nnode
            cur = cur.next
    p = head

    input()
    qn = input()
    head = None
    cur = None

    for _ in range(qn):
        cur_line = input().strip()
        nnode = Node(None,None,None)
        if cur_line[0] == "-":
            nnode.coeff = -1 * int(cur_line[1])
        else:
            nnode.coeff = cur_line[0]
        if cur_line[2] == "-":
            nnode.exp = -1 * int(cur_line[3])
        else:
            nnode.exp = cur_line[2]

        if head is None:
            head = nnode
            cur = nnode
        else:
            cur.next = nnode
            cur = cur.next
    q = head

    print(p.add(q))











if __name__ == "__main__":
    main()